// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEcMFzEt85sy20jlgt0o1O6KCUb6SQB4',
    appId: '1:204534886892:web:8d77166ab1612ee8b510c9',
    messagingSenderId: '204534886892',
    projectId: 'cleanease-2a375',
    authDomain: 'cleanease-2a375.firebaseapp.com',
    storageBucket: 'cleanease-2a375.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthDnZTirVcc-zq-19rh0MthDfcS7phQA',
    appId: '1:204534886892:android:87c6817a8c1effa7b510c9',
    messagingSenderId: '204534886892',
    projectId: 'cleanease-2a375',
    storageBucket: 'cleanease-2a375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXBJn0j9ZhcWmkXk3gqrlhRAz7aOgrhE',
    appId: '1:204534886892:ios:d52e7d5d017090c2b510c9',
    messagingSenderId: '204534886892',
    projectId: 'cleanease-2a375',
    storageBucket: 'cleanease-2a375.appspot.com',
    iosBundleId: 'com.example.freshApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXBJn0j9ZhcWmkXk3gqrlhRAz7aOgrhE',
    appId: '1:204534886892:ios:d52e7d5d017090c2b510c9',
    messagingSenderId: '204534886892',
    projectId: 'cleanease-2a375',
    storageBucket: 'cleanease-2a375.appspot.com',
    iosBundleId: 'com.example.freshApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEcMFzEt85sy20jlgt0o1O6KCUb6SQB4',
    appId: '1:204534886892:web:d65654c78cd4026db510c9',
    messagingSenderId: '204534886892',
    projectId: 'cleanease-2a375',
    authDomain: 'cleanease-2a375.firebaseapp.com',
    storageBucket: 'cleanease-2a375.appspot.com',
  );
}
